backend:
  name: git-gateway #git-gateway || test-repo
  branch: master
media_folder: public/img
public_folder: img
collections:
  - name: "settings"
    label: "Settings"
    files:
    - label: "Site options"
      name: "site_options"
      file: "settings/settings.md"
      fields:
        - { label: "Site name", name: "site_name", widget: "string"}
        - { label: "Site credits", name: "site_credits", widget: "string"}
        - label: "Social networks"
          name: "social_networks"
          widget: list
          fields:
            - { label: "Network", name: "network", widget: "string" }
            - { label: "Link", name: "link", widget: "string" }
  - name: "pages"
    label: "Pages"
    files:
    - label: "Home"
      name: "home"
      file: "content/home.md"
      fields:
        - { label: "Title", name: "title", widget: "string"}
        - { label: "Subtitle", name: "subtitle", widget: "text"}
        - label: "Featured work"
          name: "featured_work"
          widget: "relation"
          collection: "work_posts"
          search_fields: [ "work_posts.title" ]
          value_field: '{{slug}}'
          multiple: true
          max: 2
    - label: "About"
      name: "about"
      file: "content/about.md"
      fields:
        - { label: "Title", name: "title", widget: "string"}
        - { label: "Subtitle", name: "subtitle", widget: "text"}
    - label: "Work"
      name: "work"
      file: "content/work.md"
      fields:
        - { label: "Title", name: "title", widget: "string"}
        - { label: "Subtitle", name: "subtitle", widget: "text"}
    - label: "Contact"
      name: "contact"
      file: "content/contact.md"
      fields:
        - { label: "Title", name: "title", widget: "string"}
        - { label: "Subtitle", name: "subtitle", widget: "text"}
  - name: "work_posts"
    label: "Work posts"
    folder: 'content/workPosts'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: "Title", name: "title", widget: "string", required: true }
      - label: "Work post"
        name: "work_post"
        widget: "object"
        summary: '{{title}}'
        fields:
          - { label: "Subtitle", name: "subtitle", widget: "text" }
          - { label: 'Image', name: 'image', widget: 'image' }
          - { label: 'Content', name: 'content', widget: 'markdown' }
