backend:
  name: git-gateway #git-gateway || test-repo
  branch: master
media_folder: public/img
public_folder: img
collections:
  - name: "pages"
    label: "Pages"
    files:
    - label: "Home"
      name: "home"
      file: "content/home.md"
      fields:
        - { label: "Title", name: "title", widget: "string"}
        - { label: "Subtitle", name: "subtitle", widget: "text"}
        - label: "Featured work"
          name: "featuredWork"
          widget: "relation"
          collection: "work"
          search_fields: [ "workList.title" ]
          value_field: "workList.title"
          multiple: true
          max: 2
    - label: "About"
      name: "about"
      file: "content/about.md"
      fields:
        - { label: "Title", name: "title", widget: "string"}
        - { label: "Subtitle", name: "subtitle", widget: "text"}
    - label: "Work"
      name: "work"
      file: "content/work.md"
      fields:
        - { label: "Title", name: "title", widget: "string"}
        - { label: "Subtitle", name: "subtitle", widget: "text"}
        - label: "Work List"
          name: "workList"
          widget: list
          fields:
            - { label: "Name", name: "name", widget: "string" }
            - { label: "Description", name: "description", widget: "text" }
    - label: "Contact"
      name: "contact"
      file: "content/contact.md"
      fields:
        - { label: "Title", name: "title", widget: "string"}
        - { label: "Subtitle", name: "subtitle", widget: "text"}
